name: ci-build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js in Linux and Windows environments
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./validator
        
      - name: Run DevMatch validation
        run: npm run devmatch -- validate
        working-directory: ./validator

      - name: Assert results
        run: node ../.github/workflows/ci.js
        working-directory: ./validator
